packages:
  - "playground/*"
  - "compilers/*"
  - "devtools/*"
  - "extensions/*"
  - "linting/*"
  - "platforms/*"
  - "plugins/*"
  - "runtime/*"
  - "common/*"
  - "ssr/*"
  - "testing/*"
  - "cli/*"

